name: grit
favicon: null
layout_spectrum: 0.5415980969555676
typography_spectrum: 0.22213136637583375
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.01214372762478888
  lightness: 0.7783095042686909
  saturation: 0.843449299223721
  rhythmicContrast: 0.5242951705586165
purpose: []
